name: "node-depsup-action"
author: Florencea Bear
branding:
  color: blue
  icon: refresh-cw
description: "Upgrade minor/patch version packages for Node.js project"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: main ${{ github.actor }}
