name: "node-depsup-action"
author: Florencea Bear
branding:
  color: blue
  icon: refresh-cw
description: "Upgrade minor/patch version packages for Node.js project"
inputs:
  GH_TOKEN:
    description: Your GitHub token with write permission, you can use 'github.token'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: main
      env:
        GH_TOKEN: ${{ input.GH_TOKEN }}
        GH_ACTOR: ${{ github.actor }}
      shell: bash
