#! /usr/bin/env bash
set -o errexit
set -o pipefail

COMMIT_MSG_BODY="$(npx -y npm-check-updates@latest -p npm -t semver --install never | sed "1,2d; $d" | sed "$ d")"

if ! [ "$COMMIT_MSG_BODY" = "" ]; then
  printf "Upgrading package.json and package-lock.json\n"
  printf "\n$COMMIT_MSG_BODY\n\n"
  npx -y npm-check-updates@latest -p npm -t semver --install never --loglevel silent -u
  rm -f package-lock.json
  NODE_ENV=development npm i --loglevel silent
  git config user.name "$GH_ACTOR"
  git config user.email "$(gh api /users/$GH_ACTOR | jq .email -r)"
  git add package-lock.json
  git add package.json
  git commit -m "fix(deps): update all non-major dependencies" -m "$COMMIT_MSG_BODY" -m "by GitHub Action" &>/dev/null
  git push -q
else
  printf "All packages are latest :)\n"
fi
