#! /usr/bin/env bash
set -o errexit
set -o pipefail

CURRENT_TAG="$(git describe --abbrev=0 --tags)"
NEXT_TAG="$(npx -y semver@latest "$CURRENT_TAG" -i patch)"
git tag -a -m "Release v$NEXT_TAG" "v$NEXT_TAG"
git push --follow-tags
