#! /usr/bin/env bash
set -o errexit
set -o pipefail

### Check cmd exist
chkcmd "git"
chkcmd "npx"

CURRENT_TAG="$(git describe --abbrev=0 --tags)"
NEXT_TAG="$(npx -y semver@latest "$CURRENT_TAG" -i patch)"
git tag -a -m "Release $NEXT_TAG" "$NEXT_TAG"
git push --follow-tags
